### ISSUE TITLE
Potential bug in GraphicsDevice

### ISSUE THREAD

**Issue by alex-aparin** [axodox/axodox-common#3]
I learned source and came across on unclear line inside `void GraphicsDevice::InitializeDevice(const winrt::com_ptr<IDXGIFactoryT>& factory, GraphicsDeviceFlags flags, winrt::com_ptr<IDXGIAdapterT> adapter)` method

`      com_ptr<ID3D12Device> device12;
      check_hresult(D3D12CreateDevice(adapter.get(), *ranges::rend(_featureLevels), guid_of<ID3D12Device>(), device12.put_void()));`

it seems like `_featureLevels[0]` should be used. Otherwise it's undefined behaviour. Here is example https://godbolt.org/z/3rKx48Wr9 to demonstrate problem

**Comment by axodox** [comment]
It should be rbegin I think, as the last specified is the minimum. But yes, that is mistake, I have ported over my existing middleware as I plan to build 3D models with Stable Diffusion, however I have not yet started on that. So anything in the Graphics namespace will probably have some bugs.

**Comment by alex-aparin** [comment]
@axodox yeah, I thought you wanted to take first element (like *(rend() - 1). P.S. Usage of rbegin is more logical that my assumption

**Comment by axodox** [comment]
Fixed
